name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  macos:
    name: Smoke Tests

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-11

          - target: aarch64-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.79.0"

      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - uses: pypa/hatch@install

      - name: Hatch venv
        run: hatch env create

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist

      - name: Install Built Wheel
        run: hatch run pip install dist/cedar_detect-*.whl --force-reinstall

      - name: Run Tests
        run: hatch run pytest

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "cedar-detect-python-${{ matrix.os }}"
          path: dist/*.whl
