name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  checks:
    name: Smoke Tests

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: pypa/hatch@install

      - name: Local Build
        run: hatch run setup

      - name: Run Tests
        run: hatch test

      - name: Release Build
        run: hatch build -t wheel

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "cedar-detect-python-${{ matrix.os }}"
          path: dist/*.whl
