name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  checks-win-mac:
    name: Smoke Tests

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-2022
            arch: x64

          - target: i686-pc-windows-msvc
            os: windows-2022
            arch: x86

          - target: x86_64-apple-darwin
            os: macos-12
            arch: x64

          - target: aarch64-apple-darwin
            os: macos-12
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt

      - uses: arduino/setup-protoc@v3

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          architecture: ${{ matrix.arch }}

      - uses: pypa/hatch@install

      - name: Local Build
        run: hatch run setup
        env:
          CARGO_BUILD_TARGET: ${{ matrix.target }}

      - name: Run Tests
        run: hatch test

      - name: Release Build
        run: hatch build -t wheel
        env:
          CARGO_BUILD_TARGET: ${{ matrix.target }}

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "cedar-detect-python-${{ matrix.os }}"
          path: dist/*.whl
